import type { LocalImageReader } from './localImageReader';
import type { BlurMetricCalculatorSuite } from './blurMetricCalculators';
import { searchMetricThresholds } from './blurMetricThresholdEvaluator';
import { evaluateExplainableCombinations } from './blurMetricCombinationEvaluator';
import { BLUR_METRIC_BENCHMARK_CONFIG as config } from './blurMetricBenchmarkConfig';
import type { BlurBenchmarkImage, BlurMetricBenchmark, BlurMetricBenchmarkSummary, BlurMetricValue } from './blurMetricBenchmarkTypes';
import type { BlurValidationDatasetEntry, BlurValidationLabel } from './figureBlurValidationTypes';

type CalculatedImage = { file: string; expectedLabel: BlurValidationLabel; metrics: BlurMetricValue[] };
export class BlurMetricBenchmarkRunner {
  constructor(private readonly images: Pick<LocalImageReader, 'read'>, private readonly calculators: Pick<BlurMetricCalculatorSuite, 'calculate'>) {}
  async run(entries: readonly BlurValidationDatasetEntry[]): Promise<{ results: BlurBenchmarkImage[]; summary: BlurMetricBenchmarkSummary }> {
    const calculated: CalculatedImage[] = [];
    for (const entry of entries) {
      let image; try { image = await this.images.read(entry.filePath); } catch { throw new Error(`Unreadable or unsupported image: ${entry.file}`); }
      calculated.push({ file: entry.file, expectedLabel: entry.expectedLabel, metrics: await this.calculators.calculate(image) });
    }
    normalize(calculated); const first = calculated[0]; if (!first) throw new Error('Benchmark dataset is empty');
    const benchmarks = first.metrics.map((definition) => benchmarkMetric(definition, calculated)).sort(compareBenchmark);
    const imageValues = calculated.map((image) => ({ file: image.file, expectedLabel: image.expectedLabel, values: Object.fromEntries(image.metrics.map((metric) => [metric.metricId, metric.rawValue])) }));
    const combinations = evaluateExplainableCombinations(imageValues, benchmarks).slice(0, config.shortlistCombinationLimit);
    const results: BlurBenchmarkImage[] = calculated.map((image) => {
      const values = Object.fromEntries(image.metrics.map((metric) => [metric.metricId, metric.rawValue]));
      return { ...image, metricPredictions: Object.fromEntries(benchmarks.map((metric) => [metric.metricId, predict(values[metric.metricId], metric.bestBalanced.direction, metric.bestBalanced.threshold)])), combinationPredictions: Object.fromEntries(combinations.map((combination) => [combination.combinationId, predictCombination(image.metrics, combination, benchmarks)])) };
    });
    const top = benchmarks[0]; const predictions = results.map((result) => result.metricPredictions[top.metricId]);
    const falseRejectCases = results.filter((result, index) => result.expectedLabel === 'sharp' && predictions[index] === 'blurry').map((result) => ({ file: result.file, expectedLabel: 'sharp' as const, predictedLabel: 'blurry' as const, metrics: result.metrics }));
    const falseAcceptCases = results.filter((result, index) => result.expectedLabel === 'blurry' && predictions[index] === 'sharp').map((result) => ({ file: result.file, expectedLabel: 'blurry' as const, predictedLabel: 'sharp' as const, metrics: result.metrics }));
    return { results, summary: { datasetCounts: { total: results.length, sharp: results.filter((result) => result.expectedLabel === 'sharp').length, blurry: results.filter((result) => result.expectedLabel === 'blurry').length }, metricRankings: benchmarks, bestThresholdPerMetric: benchmarks.map((metric) => metric.bestBalanced), conservativeThresholdOptions: benchmarks.map((metric) => ({ metricId: metric.metricId, zeroFalseRejectIfAvailable: metric.zeroFalseRejectIfAvailable, lowestFalseAcceptWithFalseRejectRateAtMost10Percent: metric.lowestFalseAcceptWithFalseRejectRateAtMost10Percent })), shortlistedCombinations: combinations, falseRejectCases, falseAcceptCases, caveat: config.caveat } };
  }
}
function benchmarkMetric(definition: BlurMetricValue, images: CalculatedImage[]): BlurMetricBenchmark { const values = images.map((image) => ({ file: image.file, expectedLabel: image.expectedLabel, value: image.metrics.find((metric) => metric.metricId === definition.metricId)!.rawValue })); const declared = searchMetricThresholds(values, definition.metricId, definition.direction); const opposite = searchMetricThresholds(values, definition.metricId, definition.direction === 'higher_is_sharper' ? 'lower_is_sharper' : 'higher_is_sharper'); const selected = compareBalanced(declared.bestBalanced, opposite.bestBalanced) <= 0 ? declared : opposite; return { metricId: definition.metricId, displayName: definition.displayName, declaredDirection: definition.direction, simplicity: definition.simplicity, bestBalanced: selected.bestBalanced, zeroFalseRejectIfAvailable: selected.zeroFalseRejectIfAvailable, lowestFalseAcceptWithFalseRejectRateAtMost10Percent: selected.lowestFalseAcceptWithFalseRejectRateAtMost10Percent }; }
function predict(value: number, direction: 'higher_is_sharper' | 'lower_is_sharper', threshold: number): BlurValidationLabel { return (direction === 'higher_is_sharper' ? value >= threshold : value <= threshold) ? 'sharp' : 'blurry'; }
function compareBalanced(a: BlurMetricBenchmark['bestBalanced'], b: BlurMetricBenchmark['bestBalanced']) { return b.metrics.balancedAccuracy - a.metrics.balancedAccuracy || a.metrics.falseRejectRate - b.metrics.falseRejectRate || a.metrics.falseAcceptRate - b.metrics.falseAcceptRate || a.direction.localeCompare(b.direction) || a.threshold - b.threshold; }
function compareBenchmark(a: BlurMetricBenchmark, b: BlurMetricBenchmark) { return a.bestBalanced.metrics.falseRejectRate-b.bestBalanced.metrics.falseRejectRate||a.bestBalanced.metrics.falseAcceptRate-b.bestBalanced.metrics.falseAcceptRate||b.bestBalanced.metrics.balancedAccuracy-a.bestBalanced.metrics.balancedAccuracy||a.simplicity-b.simplicity||a.metricId.localeCompare(b.metricId); }
function normalize(images: CalculatedImage[]) { for (const definition of images[0]?.metrics ?? []) { const values = images.map((image) => image.metrics.find((metric) => metric.metricId === definition.metricId)!.rawValue), min = Math.min(...values), max = Math.max(...values); for (const image of images) { const metric = image.metrics.find((value) => value.metricId === definition.metricId)!; const normalized = max === min ? 0.5 : (metric.rawValue - min) / (max - min); metric.normalizedValue = definition.direction === 'higher_is_sharper' ? normalized : 1 - normalized; } } }
function predictCombination(metrics: BlurMetricValue[], combination: { combinationId: string; metricsUsed: string[]; thresholds: Record<string, number> }, benchmarks: BlurMetricBenchmark[]): BlurValidationLabel { const map = Object.fromEntries(metrics.map((metric) => [metric.metricId, metric])); const sharp = (id: string) => { const benchmark = benchmarks.find((value) => value.metricId === id)!; return predict(map[id].rawValue, benchmark.bestBalanced.direction, combination.thresholds[id]) === 'sharp'; }; let pass; if (combination.combinationId === 'and') pass = combination.metricsUsed.every(sharp); else if (combination.combinationId === 'or') pass = combination.metricsUsed.some(sharp); else if (combination.combinationId === 'two_stage') pass = sharp(combination.metricsUsed[0]) || (sharp(combination.metricsUsed[1]) && sharp(combination.metricsUsed[2])); else pass = combination.metricsUsed.reduce((sum, id) => sum + (map[id].normalizedValue ?? 0), 0) / combination.metricsUsed.length >= combination.thresholds.score; return pass ? 'sharp' : 'blurry'; }
