import sharp from 'sharp';import type { StoredImage } from './imageEmbeddingTypes';import type { PrimarySubjectBlurEvaluator } from './primarySubjectBlurEvaluator';import { BLUR_METRIC_BENCHMARK_CONFIG as config } from './blurMetricBenchmarkConfig';import type { BlurMetricValue } from './blurMetricBenchmarkTypes';
export class BlurMetricCalculatorSuite{constructor(private readonly production:Pick<PrimarySubjectBlurEvaluator,'evaluateImage'>){}async calculate(image:StoredImage):Promise<BlurMetricValue[]>{const existing=await this.production.evaluateImage(image);const prepared=await sharp(image.bytes).rotate().resize({width:config.maxAnalysisDimension,height:config.maxAnalysisDimension,fit:'inside',withoutEnlargement:true}).greyscale().raw().toBuffer({resolveWithObject:true});const p=prepared.data,w=prepared.info.width,h=prepared.info.height;const lap=laplacian(p,w,h),sob=sobel(p,w,h);const blurred=await sharp(p,{raw:{width:w,height:h,channels:1}}).blur(config.highPassSigma).raw().toBuffer();return[
 m('sharp_stats_sharpness','Sharp stats sharpness','higher_is_sharper',existing.sharpStats ?? existing.sharpnessMetric,1),m('mean_absolute_gradient','Mean absolute grayscale gradient','higher_is_sharper',existing.meanAbsoluteGradient ?? existing.detailMetric,1),m('laplacian_variance','Variance of Laplacian','higher_is_sharper',variance(lap),2),m('tenengrad','Tenengrad Sobel energy','higher_is_sharper',mean(sob.map(v=>v*v)),2),m('brenner_gradient','Brenner gradient','higher_is_sharper',brenner(p,w,h),2),m('laplacian_mean_absolute','Laplacian mean absolute response','higher_is_sharper',mean(lap.map(Math.abs)),2),m('high_frequency_residual_ratio','High-frequency residual energy ratio','higher_is_sharper',highPassRatio(p,blurred),3),m('edge_spread_width','Edge-spread width proxy','lower_is_sharper',edgeSpread(p,w,h),3),m('local_block_contrast','Local block contrast','higher_is_sharper',localContrast(p,w,h,config.localBlockSize),2)];}}
function m(metricId:string,displayName:string,direction:BlurMetricValue['direction'],rawValue:number,simplicity:number):BlurMetricValue{if(!Number.isFinite(rawValue))throw new Error(`Non-finite blur metric: ${metricId}`);return{metricId,displayName,direction,rawValue,simplicity};}
export async function calculateLaplacianVarianceMetric(image:StoredImage,maxAnalysisDimension=config.maxAnalysisDimension):Promise<number>{const prepared=await sharp(image.bytes).rotate().resize({width:maxAnalysisDimension,height:maxAnalysisDimension,fit:'inside',withoutEnlargement:true}).greyscale().raw().toBuffer({resolveWithObject:true});return variance(laplacian(prepared.data,prepared.info.width,prepared.info.height));}
function laplacian(p:Buffer,w:number,h:number){const out:number[]=[];for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x;out.push(p[i-w]+p[i-1]-4*p[i]+p[i+1]+p[i+w]);}return out;}
function sobel(p:Buffer,w:number,h:number){const out:number[]=[];for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x,gx=-p[i-w-1]+p[i-w+1]-2*p[i-1]+2*p[i+1]-p[i+w-1]+p[i+w+1],gy=-p[i-w-1]-2*p[i-w]-p[i-w+1]+p[i+w-1]+2*p[i+w]+p[i+w+1];out.push(Math.hypot(gx,gy));}return out;}
function brenner(p:Buffer,w:number,h:number){let total=0,n=0;for(let y=0;y<h-2;y++)for(let x=0;x<w-2;x++){const i=y*w+x,dx=p[i+2]-p[i],dy=p[i+2*w]-p[i];total+=dx*dx+dy*dy;n+=2;}return n?total/n:0;}
function highPassRatio(p:Buffer,b:Buffer){let hi=0,total=0,avg=mean([...p]);for(let i=0;i<p.length;i++){hi+=(p[i]-b[i])**2;total+=(p[i]-avg)**2;}return total?hi/total:0;}
function edgeSpread(p:Buffer,w:number,h:number){const gradients:number[]=[];for(let y=0;y<h;y++)for(let x=1;x<w;x++)gradients.push(Math.abs(p[y*w+x]-p[y*w+x-1]));gradients.sort((a,b)=>a-b);const threshold=gradients[Math.floor(gradients.length*.9)]??0;if(!threshold)return Number.MAX_SAFE_INTEGER;let weighted=0,peaks=0;for(let y=0;y<h;y++)for(let x=1;x<w-1;x++){const i=y*w+x,g=Math.abs(p[i+1]-p[i-1])/2;if(g>=threshold){const curvature=Math.abs(p[i-1]-2*p[i]+p[i+1]);weighted+=g/(curvature+1e-9);peaks++;}}return peaks?weighted/peaks:Number.MAX_SAFE_INTEGER;}
function localContrast(p:Buffer,w:number,h:number,size:number){const values=[];for(let top=0;top<h;top+=size)for(let left=0;left<w;left+=size){const block=[];for(let y=top;y<Math.min(h,top+size);y++)for(let x=left;x<Math.min(w,left+size);x++)block.push(p[y*w+x]);values.push(Math.sqrt(variance(block)));}return mean(values);}
function mean(v:number[]){return v.length?v.reduce((a,b)=>a+b,0)/v.length:0;}function variance(v:number[]){if(!v.length)return 0;const a=mean(v);return mean(v.map(x=>(x-a)**2));}
