import type { BlurFixedPolicy } from './blurFixedPolicyEvaluator';
export type BlurMetricBenchmarkCliOptions={datasetDir:string;outputDir:string;overwrite:boolean;fixedPolicy:boolean;fixedPolicyConfig?:BlurFixedPolicy};
export function parseBlurMetricBenchmarkArgs(args:string[]):BlurMetricBenchmarkCliOptions {
  let datasetDir:string|undefined,outputDir:string|undefined,overwrite=false,fixedPolicy=false,primaryMetric:string|undefined,secondaryMetric:string|undefined,decisionRule:'and'|'or'|undefined;let primaryThreshold:number|undefined,secondaryThreshold:number|undefined;
  for(let i=0;i<args.length;i++){const option=args[i];if(option==='--dataset-dir')datasetDir=value(args[++i],option);else if(option==='--output-dir')outputDir=value(args[++i],option);else if(option==='--overwrite')overwrite=true;else if(option==='--fixed-policy')fixedPolicy=true;else if(option==='--primary-metric')primaryMetric=value(args[++i],option);else if(option==='--primary-threshold')primaryThreshold=numeric(value(args[++i],option),option);else if(option==='--secondary-metric')secondaryMetric=value(args[++i],option);else if(option==='--secondary-threshold')secondaryThreshold=numeric(value(args[++i],option),option);else if(option==='--decision-rule'){const rule=value(args[++i],option);if(rule!=='and'&&rule!=='or')throw new Error('--decision-rule must be and or or');decisionRule=rule;}else throw new Error(`Unknown option: ${option}`);}
  if(!datasetDir||!outputDir)throw new Error('--dataset-dir and --output-dir are required');const supplied=[primaryMetric,primaryThreshold,secondaryMetric,secondaryThreshold,decisionRule].some(item=>item!==undefined);if(fixedPolicy&&(!primaryMetric||primaryThreshold===undefined||!secondaryMetric||secondaryThreshold===undefined||!decisionRule))throw new Error('Fixed policy requires both metrics, both thresholds, and a decision rule');if(!fixedPolicy&&supplied)throw new Error('Fixed-policy arguments requires --fixed-policy');
  return{datasetDir,outputDir,overwrite,fixedPolicy,fixedPolicyConfig:fixedPolicy?{primaryMetric:primaryMetric!,primaryThreshold:primaryThreshold!,secondaryMetric:secondaryMetric!,secondaryThreshold:secondaryThreshold!,decisionRule:decisionRule!}:undefined};
}
function value(v:string|undefined,o:string){if(!v||v.startsWith('--'))throw new Error(`${o} requires a value`);return v;}function numeric(v:string,o:string){const parsed=Number(v);if(!Number.isFinite(parsed))throw new Error(`${o} requires a finite number`);return parsed;}
export function formatBlurMetricBenchmarkSummary(s:{datasetCounts:{total:number};metricRankings:Array<{metricId:string}>;shortlistedCombinations:Array<{combinationId:string}>;falseRejectCases:unknown[];falseAcceptCases:unknown[]}):string[]{return['Blur metric benchmark summary',JSON.stringify({datasetSize:s.datasetCounts.total,topIndividualMetrics:s.metricRankings.slice(0,5).map(m=>m.metricId),topExplainableCombinations:s.shortlistedCombinations.slice(0,5).map(c=>c.combinationId),falseRejectCount:s.falseRejectCases.length,falseAcceptCount:s.falseAcceptCases.length})];}
export function formatBlurFixedPolicySummary(summary:unknown):string[]{return['Fixed Holdout Policy Evaluation',JSON.stringify(summary)];}
