'use strict';
const {describe,it}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {validateCalibrationInput}=require('../lib/figureRecognition/retrievalCalibrationInput');
const {decideCalibrationOutcome,evaluateCalibrationPolicy,generateCalibrationPolicies,calibrationDiagnostics}=require('../lib/figureRecognition/retrievalCalibrationAnalyzer');
const {compareCalibrationPolicies,paretoPolicies,shortlist}=require('../lib/figureRecognition/retrievalCalibrationRanking');const {writeCalibrationOutputs,toCsv}=require('../lib/figureRecognition/retrievalCalibrationWriter');
const {analyzeRetrievalQuality,formatRetrievalQuality}=require('../lib/figureRecognition/retrievalQualityAnalyzer');
const row=(o={})=>({id:'case-1',catalogPresence:'present',expectedFigureId:'expected',status:'completed',top1Correct:true,top1Distance:.18,top2Distance:.25,top1Top2Gap:.07,relativeTop1Top2Gap:.28,distanceSpread:.1,policyVersion:'shadow-v1',calibrationProfile:'default',...o});
const sample=(o={})=>validateCalibrationInput([row(o)]).samples[0];
const policy=(shape,thresholds)=>({id:shape,shape,thresholds,complexity:2});
describe('calibration input',()=>{
 it('validates labels, finite evidence, duplicates, and consistent metadata',()=>{assert.equal(validateCalibrationInput([row(),row({id:'absent',catalogPresence:'absent',expectedFigureId:undefined,top1Correct:undefined})]).samples.length,2);assert.throws(()=>validateCalibrationInput([row(),row()]),/Duplicate/);assert.throws(()=>validateCalibrationInput([row({top1Distance:NaN})]),/non-finite/);assert.throws(()=>validateCalibrationInput([row({policyVersion:'a'}),row({id:'two',policyVersion:'b'})]),/mixed/);assert.throws(()=>validateCalibrationInput([row({catalogPresence:'absent'})]),/must not/);});
 it('counts failed, isolation-rejected, and incomplete exclusions',()=>{const x=validateCalibrationInput([row({status:'failed'}),row({id:'two',status:'isolation_rejected'}),row({id:'three',top1Distance:undefined}),row({id:'four'})]);assert.equal(x.samples.length,1);assert.deepEqual([x.summary.excludedFailed,x.summary.excludedIsolationRejected,x.summary.excludedIncompleteEvidence],[1,1,1]);});
});
describe('policy semantics',()=>{
 it('evaluates all four explainable shapes with inclusive boundaries',()=>{const s=sample({top1Distance:.2,top1Top2Gap:.05,relativeTop1Top2Gap:.2});assert.equal(decideCalibrationOutcome(s,policy('distance_and_relative_gap',{maximumTop1Distance:.2,minimumRelativeGap:.2})),'high_confidence');assert.equal(decideCalibrationOutcome(s,policy('distance_and_absolute_gap',{maximumTop1Distance:.2,minimumAbsoluteGap:.05})),'high_confidence');assert.equal(decideCalibrationOutcome(s,policy('distance_and_either_margin',{maximumTop1Distance:.2,minimumAbsoluteGap:.06,minimumRelativeGap:.2})),'high_confidence');assert.equal(decideCalibrationOutcome(s,policy('strong_distance_or_distance_with_relative_gap',{maximumTop1Distance:.22,strongDistance:.2,minimumRelativeGap:.9})),'high_confidence');});
 it('handles missing Top-2 evidence and zero distance deterministically',()=>{const p=policy('distance_and_relative_gap',{maximumTop1Distance:.2,minimumRelativeGap:.1});assert.equal(decideCalibrationOutcome(sample({top1Top2Gap:undefined,relativeTop1Top2Gap:undefined}),p),'needs_review');assert.equal(decideCalibrationOutcome(sample({top1Distance:0,top1Top2Gap:undefined,relativeTop1Top2Gap:undefined}),policy('strong_distance_or_distance_with_relative_gap',{maximumTop1Distance:.2,strongDistance:0,minimumRelativeGap:.1})),'high_confidence');});
 it('generates a stable, unique centralized grid',()=>{const a=generateCalibrationPolicies(),b=generateCalibrationPolicies();assert.ok(a.length>1000);assert.equal(new Set(a.map(x=>x.id)).size,a.length);assert.deepEqual(a,b);});
});
describe('metrics and ranking',()=>{
 const p=policy('distance_and_relative_gap',{maximumTop1Distance:.2,minimumRelativeGap:.1});
 it('counts correct accepts, incorrect accepts, absent accepts, review, and no-match',()=>{const samples=[sample(),sample({id:'bad',top1Correct:false}),sample({id:'abs',catalogPresence:'absent',expectedFigureId:undefined,top1Correct:undefined}),sample({id:'review',relativeTop1Top2Gap:.01}),sample({id:'no',top1Distance:.3})];const m=evaluateCalibrationPolicy(samples,p).metrics;assert.deepEqual([m.highConfidenceCount,m.falseAcceptCount,m.needsReviewCount,m.noConfidentMatchCount],[3,2,1,1]);assert.equal(m.highConfidencePrecision,1/3);assert.deepEqual(calibrationDiagnostics(samples,p).falseAcceptCaseIds,['bad','abs']);});
 it('orders conservatively, computes Pareto policies, and attaches shortlist diagnostics',()=>{const samples=[sample()];const a=evaluateCalibrationPolicy(samples,{...p,id:'a'}),b={...evaluateCalibrationPolicy(samples,{...p,id:'b'}),metrics:{...a.metrics,falseAcceptCount:1}};assert.equal([b,a].sort(compareCalibrationPolicies)[0].id,'a');assert.deepEqual(paretoPolicies([a,b]).map(x=>x.id),['a']);assert.equal(shortlist([a],samples,()=>true)[0].diagnostics.correctHighConfidenceCaseIds[0],'case-1');});
});
describe('outputs',()=>{it('writes bounded JSON/CSV artifacts, escapes CSV, protects existing files, and contains no unsafe fields',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'calibration-'));try{const result=evaluateCalibrationPolicy([sample()],policy('distance_and_relative_gap',{maximumTop1Distance:.2,minimumRelativeGap:.1}));assert.match(toCsv([{...result,id:'policy,"quoted"'}]),/"policy,""quoted"""/);await writeCalibrationOutputs(dir,[result],{safe:true});const text=await fs.readFile(path.join(dir,'calibration-policy-results.csv'),'utf8');assert.match(text,/maximumTop1Distance/);assert.doesNotMatch(text,/image|vector|url/i);assert.deepEqual(JSON.parse(await fs.readFile(path.join(dir,'calibration-summary.json'),'utf8')),{safe:true});await assert.rejects(()=>writeCalibrationOutputs(dir,[result],{}),/already exists/);await writeCalibrationOutputs(dir,[result],{},true);}finally{await fs.rm(dir,{recursive:true,force:true});}});});

describe('dataset retrieval quality',()=>{
 const presentSample=(id,ip,series,rank,distance=.2)=>({id,catalogPresence:'present',expectedFigureId:`expected-${id}`,expectedIpId:ip,expectedSeriesId:series,expectedRank:rank,top1Correct:rank===1,top1FigureId:rank===1?`expected-${id}`:`wrong-${id}`,top1SeriesId:rank===1?series:'wrong-series',top1IpId:rank===1?ip:'wrong-ip',top1Distance:distance,policyVersion:'v',calibrationProfile:'p'});
 it('computes overall present and absent quality with safe denominators',()=>{const report=analyzeRetrievalQuality([presentSample('a','hirono','mime',1,.1),presentSample('b','hirono','mime',3,.3),presentSample('c','skullpanda','city',undefined,.5),{id:'abs',catalogPresence:'absent',top1FigureId:'candidate',top1Distance:.4,policyVersion:'v',calibrationProfile:'p'}]);const p=report.overall.catalogPresent;assert.deepEqual({top1:p.top1Accuracy,top3:p.top3Accuracy,top5:p.top5Accuracy,mrr:p.meanReciprocalRank,average:p.averageTop1Distance,median:p.medianTop1Distance},{top1:1/3,top3:2/3,top5:2/3,mrr:4/9,average:.3,median:.3});assert.deepEqual(report.overall.catalogAbsent,{cases:1,falseTop1Rate:1,averageTop1Distance:.4});});
 it('groups by expected IP and Series by case count and retains small groups',()=>{const report=analyzeRetrievalQuality([presentSample('a','hirono','mime',1),presentSample('b','hirono','echo',2),presentSample('c','skullpanda','city',undefined)]);assert.deepEqual(report.accuracyByIp.map(g=>[g.id,g.cases,g.top1Accuracy]),[['hirono',2,.5],['skullpanda',1,0]]);assert.deepEqual(report.accuracyBySeries.map(g=>[g.id,g.cases]),[['city',1],['echo',1],['mime',1]]);assert.equal(report.summary.worstPerformingIp,'skullpanda');});
 it('reports and sorts hard failures by retrieved rank then distance, with not-retrieved last',()=>{const report=analyzeRetrievalQuality([presentSample('missing','hirono','mime',undefined,.1),presentSample('rank4','hirono','echo',4,.3),presentSample('rank2','skullpanda','city',2,.4),presentSample('correct','dimoo','world',1,.2)]);assert.deepEqual(report.hardFailures.map(f=>f.caseId),['rank2','rank4','missing']);assert.equal(report.hardFailures[2].correctRank,undefined);const output=formatRetrievalQuality(report).join('\n');assert.match(output,/Overall Retrieval Quality[\s\S]*Accuracy by IP[\s\S]*Accuracy by Series[\s\S]*Hard Retrieval Failures/);assert.match(output,/Correct Rank: Not Retrieved[\s\S]*Embedding Quality Summary/);});
 it('derives expected taxonomy only from the matching returned candidate',()=>{const validated=validateCalibrationInput([row({expectedRank:2,top1Correct:false,top1FigureId:'wrong',top1SeriesId:'wrong-series',returnedCandidates:[{figureId:'wrong',seriesId:'wrong-series',ipId:'wrong-ip',rank:1},{figureId:'expected',seriesId:'expected-series',ipId:'expected-ip',rank:2}]})]).samples[0];assert.deepEqual({rank:validated.expectedRank,series:validated.expectedSeriesId,ip:validated.expectedIpId,topIp:validated.top1IpId},{rank:2,series:'expected-series',ip:'expected-ip',topIp:'wrong-ip'});});
});
