// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGvx4qP2ofB0Xko592nlDZxqfs1lMpldA',
    appId: '1:1094225908408:web:cdd95149a3066f98c81a4d',
    messagingSenderId: '1094225908408',
    projectId: 'blindbox-collection',
    authDomain: 'blindbox-collection.firebaseapp.com',
    storageBucket: 'blindbox-collection.firebasestorage.app',
    measurementId: 'G-080Y8Y6XR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjD8A5Mwp_dck6oIkuWnLuohfgoKc1KWs',
    appId: '1:1094225908408:android:f6c0224f6ddd7ad2c81a4d',
    messagingSenderId: '1094225908408',
    projectId: 'blindbox-collection',
    storageBucket: 'blindbox-collection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCloi6vmkrxbwnyxJlzbuIHDtlWxuk98Ko',
    appId: '1:1094225908408:ios:d3f0009f898aa355c81a4d',
    messagingSenderId: '1094225908408',
    projectId: 'blindbox-collection',
    storageBucket: 'blindbox-collection.firebasestorage.app',
    iosBundleId: 'com.example.blindboxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCloi6vmkrxbwnyxJlzbuIHDtlWxuk98Ko',
    appId: '1:1094225908408:ios:d3f0009f898aa355c81a4d',
    messagingSenderId: '1094225908408',
    projectId: 'blindbox-collection',
    storageBucket: 'blindbox-collection.firebasestorage.app',
    iosBundleId: 'com.example.blindboxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGvx4qP2ofB0Xko592nlDZxqfs1lMpldA',
    appId: '1:1094225908408:web:cd28ddc6dafb8605c81a4d',
    messagingSenderId: '1094225908408',
    projectId: 'blindbox-collection',
    authDomain: 'blindbox-collection.firebaseapp.com',
    storageBucket: 'blindbox-collection.firebasestorage.app',
    measurementId: 'G-ZXZ187DDRM',
  );
}
